import {
  BsLaptop,
  BsHeartPulse,
  BsMegaphone,
  BsBriefcase,
  BsBook,
  BsTranslate,
  BsGear,
  BsNewspaper,
  BsPeople,
  BsCashCoin,
  BsCalculator,
  BsPalette,
  BsGraphUpArrow,
  BsBuilding,
  BsClipboardData,
  BsGlobe2,
  BsShieldCheck,
  BsExclamationTriangle,
  BsPersonHeart,
  BsTruck,
  BsMortarboard,
  BsHospital,
  BsFlower1,
  BsCupHot,
} from "react-icons/bs";

const majors = [
  { name: "الحاسب", icon: BsLaptop },
  { name: "الطب", icon: BsHeartPulse },
  { name: "الإدارة", icon: BsClipboardData },
  { name: "الموارد البشرية", icon: BsPeople },
  { name: "المالية", icon: BsCashCoin },
  { name: "المحاسبة", icon: BsCalculator },
  { name: "التأمين", icon: BsShieldCheck },
  { name: "إدارة المخاطر", icon: BsExclamationTriangle },
  { name: "التسويق", icon: BsMegaphone },
  { name: "إدارة الأعمال", icon: BsBuilding },
  { name: "الاقتصاد", icon: BsGraphUpArrow },
  { name: "نظم المعلومات الإدارية", icon: BsClipboardData },
  { name: "سلاسل الإمداد واللوجستيات", icon: BsTruck },
  { name: "قانون ومحاماة", icon: BsBriefcase },
  { name: "الخدمة الاجتماعية", icon: BsPersonHeart },
  { name: "التعليم", icon: BsMortarboard },
  { name: "التصميم", icon: BsPalette },
  { name: "اللغة العربية", icon: BsBook },
  { name: "اللغة الإنجليزية", icon: BsTranslate },
  { name: "الشريعة والدين", icon: BsBook },
  { name: "الهندسة", icon: BsGear },
  { name: "العلوم", icon: BsBook },
  { name: "العلوم الصحية", icon: BsHospital },
  { name: "العلوم البيئية", icon: BsFlower1 },
  { name: "علوم الأغذية", icon: BsCupHot },
  { name: "الصحافة والإعلام", icon: BsNewspaper },
  { name: "العلاقات العامة", icon: BsGlobe2 },
  { name: "السياحة والضيافة", icon: BsGlobe2 },
  { name: "الأمن والسلامة", icon: BsShieldCheck },
];

export default majors;
